---
- name: Include section 1 filesystem tasks
  ansible.builtin.import_tasks: section1_filesystem.yml
  tags: [section1, filesystem]

- name: Include section 2 services tasks
  ansible.builtin.import_tasks: section2_services.yml
  tags: [section2, services]

- name: Include section 3 network tasks
  ansible.builtin.import_tasks: section3_network.yml
  tags: [section3, network]

- name: Include section 4 logging tasks
  ansible.builtin.import_tasks: section4_logging.yml
  tags: [section4, logging]

- name: Include section 5 access tasks
  ansible.builtin.import_tasks: section5_access.yml
  tags: [section5, access]

- name: Include section 6 sysctl tasks
  ansible.builtin.import_tasks: section6_sysctl.yml
  tags: [section6, sysctl]
