---
- name: "2.1.1 | Ensure xinetd is not installed"
  ansible.builtin.apt:
    name: xinetd
    state: absent
  when: cis_rhel_2_1_1_disable_xinetd
  tags: [level1, scored, rule_2_1_1]

- name: "2.2.1 | Ensure chrony is installed"
  ansible.builtin.apt:
    name: chrony
    state: present
    update_cache: true
  when: cis_rhel_2_2_1_ntpd
  tags: [level1, scored, rule_2_2_1]

- name: "2.2.1 | Ensure chrony is enabled and running"
  ansible.builtin.service:
    name: chrony
    state: started
    enabled: true
  when: cis_rhel_2_2_1_ntpd
  tags: [level1, scored, rule_2_2_1]

- name: "2.3.1 | Ensure MTA is local-only"
  ansible.builtin.lineinfile:
    dest: /etc/postfix/main.cf
    regexp: "^(#)?inet_interfaces"
    line: "inet_interfaces = loopback-only"
    state: present
  when: cis_rhel_2_3_1_mta_localhost
  notify: Restart postfix
  tags: [level1, scored, rule_2_3_1]
