---
- name: "4.1.1 | Ensure auditd is installed"
  ansible.builtin.apt:
    name: auditd
    state: present
    update_cache: true
  when: cis_rhel_4_1_1_auditd
  tags: [level2, scored, rule_4_1_1]

- name: "4.1.1 | Ensure auditd is enabled and running"
  ansible.builtin.service:
    name: auditd
    state: started
    enabled: true
  when: cis_rhel_4_1_1_auditd
  tags: [level2, scored, rule_4_1_1]

- name: "4.2.1 | Ensure rsyslog is installed"
  ansible.builtin.apt:
    name: rsyslog
    state: present
    update_cache: true
  when: cis_rhel_4_2_1_rsyslog
  tags: [level1, scored, rule_4_2_1]

- name: "4.2.1 | Ensure rsyslog is enabled and running"
  ansible.builtin.service:
    name: rsyslog
    state: started
    enabled: true
  when: cis_rhel_4_2_1_rsyslog
  tags: [level1, scored, rule_4_2_1]
