---
- name: Verify CIS controls applied
  hosts: all
  become: true
  tasks:
    - name: Check cramfs is blacklisted
      ansible.builtin.command: grep -r "install cramfs" /etc/modprobe.d/
      changed_when: false

    - name: Check IP forwarding is disabled
      ansible.builtin.command: sysctl net.ipv4.ip_forward
      register: ipfwd
      failed_when: "'= 1' in ipfwd.stdout"
      changed_when: false

    - name: Check SSH PermitRootLogin is no
      ansible.builtin.command: grep "^PermitRootLogin no" /etc/ssh/sshd_config
      changed_when: false

    - name: Check rsyslog is running
      ansible.builtin.command: systemctl is-active rsyslog
      register: rsyslog_status
      failed_when: rsyslog_status.stdout != 'active'
      changed_when: false
